all: 	0-busy\
	1a-fork \
	1-heehaho \
	2-ParentChild \
	3-ParentChild2 \
	4-SingleExecvp \
	5-exec-list \
	6-execvp-2 \
	7-signal1 \
	8-signal2 \
	9-thoryvos

0-busy: 0-busy.c
	gcc -g 0-busy.c -o 0-busy

1a-fork: 1a-fork.c
	gcc -g 1a-fork.c -o 1a-fork

1-heehaho: 1-heehaho.c
	gcc -g 	1-heehaho.c -o 1-heehaho

2-ParentChild: 2-ParentChild.c
	gcc -g 2-ParentChild.c -o 2-ParentChild

3-ParentChild2:	3-ParentChild2.c
	gcc -g 3-ParentChild2.c -o 3-ParentChild2

4-SingleExecvp: 4-SingleExecvp.c
	gcc -g 4-SingleExecvp.c -o 4-SingleExecvp

5-exec-list: 5-exec-list.c
	gcc -g 5-exec-list.c -o 5-exec-list

6-execvp-2: 6-execvp-2.c
	gcc -g 6-execvp-2.c -o 6-execvp-2

7-signal1: 7-signal1.c
	gcc -g 7-signal1.c -o 7-signal1

8-signal2: 8-signal2.c
	gcc -g 8-signal2.c -o 8-signal2

9-thoryvos: 9-thoryvos.c
	gcc -g 9-thoryvos.c -o 9-thoryvos

clean:
	rm -f 	\
		0-busy \
		1-heehaho \
		2-ParentChild \
		3-ParentChild2 \
		4-SingleExecvp \
		5-exec-list \
		6-execvp-2 \
		7-signal1 \
		8-signal2 \
		9-thoryvos \
		a.out
