#
# Makefile
#
# Type  make    to compile all the programs
# in the chapter
#

all: 		\
		p44-pipes0 \
		p46-pipes1 \
		p48-pipes2 \
		p50-example-pipes \
		p53-pipes-dup \
		p56-pipesize \
		p60-file-pipes-exec \
		p64-demo-trick \

clean:
	rm -f 	p07-getlimits\
		p09-processIDs \
		p12-exit \
		p15-fork \
		p16-fork2 \
		p17-mychain \
		p19-treeOfProcesses \
		p21-myorphan \
		p24-wait \
		p27-waitpid \
		p29-wait-tradi \
		p31-zombies \
		p36-exec-ls \
		p37-execvp-date \
		p39-bintree \
		p44-pipes0 \
		p46-pipes1 \
		p48-pipes2 \
		p50-example-pipes \
		p53-pipes-dup \
		p56-pipesize \
		p60-file-pipes-exec \
		p64-demo-trick \
		p70-receivemessages \
		p72-sendmessages

p07-getlimits: p07-getlimits.c
	gcc -g p07-getlimits.c -o p07-getlimits

p09-processIDs: p09-processIDs.c
	gcc -g p09-processIDs.c -o p09-processIDs

p12-exit: p12-exit.c
	gcc -g p12-exit.c -o p12-exit

p15-fork: p15-fork.c
	gcc -g p15-fork.c -o p15-fork

p16-fork2: p16-fork2.c
	gcc -g p16-fork2.c -o p16-fork2

p17-mychain: p17-mychain.c
	gcc -g p17-mychain.c -o p17-mychain

p19-treeOfProcesses: p19-treeOfProcesses.c
	gcc -g p19-treeOfProcesses.c -o p19-treeOfProcesses

p21-myorphan: p21-myorphan.c
	gcc -g p21-myorphan.c -o p21-myorphan

p24-wait: p24-wait.c
	gcc -g p24-wait.c -o p24-wait

p27-waitpid: p27-waitpid.c
	gcc -g p27-waitpid.c -o p27-waitpid

p29-wait-tradi: p29-wait-tradi.c
	gcc -g p29-wait-tradi.c -o p29-wait-tradi

p31-zombies: p31-zombies.c
	gcc -g p31-zombies.c -o p31-zombies

p36-exec-ls: p36-exec-ls.c
	gcc -g p36-exec-ls.c -o p36-exec-ls

p37-execvp-date: p37-execvp-date.c
	gcc -g p37-execvp-date.c -o p37-execvp-date

p39-bintree: p39-bintree.c
	gcc -g p39-bintree.c -o p39-bintree

p44-pipes0: p44-pipes0.c
	gcc -g p44-pipes0.c -o p44-pipes0

p46-pipes1: p46-pipes1.c
	gcc -g p46-pipes1.c -o p46-pipes1

p48-pipes2: p48-pipes2.c
	gcc -g p48-pipes2.c -o p48-pipes2

p50-example-pipes: p50-example-pipes.c
	gcc -g p50-example-pipes.c -o p50-example-pipes

p53-pipes-dup: p53-pipes-dup.c
	gcc -g p53-pipes-dup.c -o p53-pipes-dup

p56-pipesize: p56-pipesize.c
	gcc -g p56-pipesize.c -o p56-pipesize

p60-file-pipes-exec: p60-file-pipes-exec.c
	gcc -g p60-file-pipes-exec.c -o p60-file-pipes-exec

p64-demo-trick: p64-demo-trick.c
	gcc -g p64-demo-trick.c -o p64-demo-trick

p70-receivemessages: p70-receivemessages.c
	gcc -g p70-receivemessages.c -o p70-receivemessages

p72-sendmessages: p72-sendmessages.c
	gcc -g p72-sendmessages.c -o p72-sendmessages
